import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'

import React , { useEffect , useState , Component  } from 'react'


export default function Home() {

    useEffect(() => {
        window.OneSignal = window.OneSignal || [];
        OneSignal.push(function () {
            OneSignal.init({
              appId: "e35b2ffc-9759-4c95-ab5e-7ad4cff7c2af",
              safari_web_id: "web.onesignal.auto.5093406a-927f-4c57-a877-608b6718a7cc",
                notifyButton: {
                    enable: true,
                },
    
                allowLocalhostAsSecureOrigin: true,
            });
        });
    
        return () => {
            window.OneSignal = undefined;
        };
    }, []); // <-- run this effect once on mount


  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></Script> 
              
      <main >
ddsds
      </main>


    </div>
  )
}







